apiVersion: v1
kind: Service
metadata:
  labels:
    app: discord-oidc
  name: discord-oidc-svc
spec:
  type: ClusterIP
  ports:
  - name: discord-oidc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: discord-oidc
